### ISSUE TITLE
Not available in Melpa

### ISSUE THREAD

**Issue by yoacompsci** [redguardtoo/company-ctags#1]
Hi Chen, I try to install but didn't found in MELPA. M-x package-list-packages doesn't show any package with "company-ctags" name.
Thanks
PD: Looks great, simple configuration for code navigation and completion with counsel-etags and company-ctags.

**Comment by redguardtoo** [comment]
Thanks for asking. It's still under review by melpa now. Check latest README, you can install it in different way.

**Comment by redguardtoo** [comment]
It's in melpa now.
