### ISSUE TITLE
Support non-prefix completion?

### ISSUE THREAD

**Issue by AmaiKinono** [redguardtoo/company-ctags#2]
Let me explain my workflow first: I only use `company-dabbrev` or `company-dabbrev-code` as my backend. They are efficient, since for a symbol, I only need to type the full name once.

When I can't remember the exact name of a symbol (like when typing it for the first time), I use this command 

``` emacs-lisp
(defun my-counsel-company ()
  (interactive)
  (company-abort)
  (let ((company-backends '(company-capf)))
    (call-interactively 'counsel-company)))
```

What's really good about `company-capf` is it supports non-prefix completion. Like if there's a symbol called `some-long-function-name` and I don't remember it starts with `some`, I can type `function` first, then further filter the results:

![counsel-company](https://user-images.githubusercontent.com/28714352/73334484-c9277780-42a7-11ea-85da-7378e3501cb3.gif)

Now I'm trying out `company-ctags` (assuming it's very suitable for large projects), but found it doesn't support non-prefix completion, which matters a lot to me. Could we make this happen?

**Comment by redguardtoo** [comment]
What's `counsel-company`?

I can give you a boolean flag `company-ctags-no-prefix-completion-p`, Is it OK for you?

**Comment by AmaiKinono** [comment]
It's a company frontend offerd by counsel. Basically you type your prefix, call this, then you can use ivy to do all sorts of filtering in the candidates, so I found it to be very handy with backends that support non-prefix completion.

> I can give you a boolean flag `company-ctags-no-prefix-completion-p`

I don' quite understand. Is it a user option or a probe?

**Comment by redguardtoo** [comment]
It's a user option.

**Comment by AmaiKinono** [comment]
> It's a user option.

That's exactly what I want.

**Comment by redguardtoo** [comment]
9ee04b1 can fuzzy match candidates (Chen Bin)

**Comment by AmaiKinono** [comment]
This works. Thanks!
