### ISSUE TITLE
Support multiple tags file?

### ISSUE THREAD

**Issue by AmaiKinono** [redguardtoo/company-ctags#3]
Now `company-ctags` finds TAGS file automatically based on `company-ctags-tags-file-name`, and seems I can add another one using `tags-file-name`. But this may be not enough. Think about these situations:

1. The TAGS file may not exist in the project directory. Some people may put all their TAGS files together for easy management.
2. We may want to create TAGS files for system header files or external dependencies, and for one project, there may be more than 1 of these TAGS files.

I'd suggest we have a variable to put a list of absolute paths of TAGS files, and an option to control whether automatically find TAGS file or not. By customize these variables in `.dir-locals.el`, the user should be able to handle any situation.

**Comment by redguardtoo** [comment]
Yeah, let me think about this.

**Comment by redguardtoo** [comment]
1b993b0 company-ctags support multiple tags files (Chen Bin)

**Comment by AmaiKinono** [comment]
This makes company-ctags can't do completion at all. It's because [L342](https://github.com/redguardtoo/company-ctags/blob/d590302bbd8a66b41ce538a17a26d6944a17bd0a/company-ctags.el#L342):

``` emacs-lisp
(extra-tags-files (ff-list-replace-env-vars company-ctags-extra-tags-files))
```

`find-file` needs to be required to make this work.

**Comment by redguardtoo** [comment]
f572d71 fixed extra tags problem (Chen Bin)

**Comment by AmaiKinono** [comment]
This works. I'll close the issue then.
