### ISSUE TITLE
The message "TAGS is loaded." prevents candidates from pop up

### ISSUE THREAD

**Issue by AmaiKinono** [redguardtoo/company-ctags#7]
When I first call `company-ctags`, there is a "TAGS is loaded" message. If I don't do anything, it disappears after several seconds, and the candidates pop up.

![1](https://user-images.githubusercontent.com/28714352/73733449-edd39180-4776-11ea-991f-6959d2023e9f.gif)

But the actual loading process is very quick. If I press up or down immediately, the candidates will show up:

![2](https://user-images.githubusercontent.com/28714352/73733490-0a6fc980-4777-11ea-827e-36218304cbfa.gif)

**Comment by redguardtoo** [comment]
d590302 be quiet by default (Chen Bin)

**Comment by AmaiKinono** [comment]
This works. I'll close the issue then.
