### ISSUE TITLE
Symbol's function definition is void: company-begin backend

### ISSUE THREAD

**Issue by patryk94** [redguardtoo/company-ctags#9]
Getting the error in the title trying to launch 
`M-x company-ctags`

My current setup in the .emacs
`
(add-to-list 'load-path "~/.emacs.d/plugins/company-ctags/")
(require 'company-ctags)
(with-eval-after-load 'company
  (company-ctags-auto-setup))
`

Tried
`
with-eval-after-load 'company
  (add-to-list 'company-backends))
`

but gave me no luck. Any ideas?

**Comment by redguardtoo** [comment]
You need install and set up `company-mode` first. Check my updated README.

Besides, you could use https://melpa.org to install the package.
